name: DedBackendDeployer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/prod.key
        chmod 600 ~/.ssh/prod.key
        cat >>~/.ssh/config <<END
        Host prod_backend
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/prod.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USERNAME }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    - name: Run scripts
      run: ssh prod_backend 'cd /opt/scripts && sh ./server_deploy_laravel.sh'
